version: '3.8'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aplusfamily
      MYSQL_DATABASE: db_health
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/db_health.sql:/docker-entrypoint-initdb.d/db_health.sql


volumes:
  db_data:
