apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app.kubernetes.io/name: MySQL
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: MySQL
  template:
    metadata:
      labels:
        app.kubernetes.io/name: MySQL
    spec:
      containers:
        - name: mysql
          image: "mysql:8.0"
          ports:
            - containerPort: {{ .Values.database.targetPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: DB_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: DB_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-init-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.database.pvc.name }}
        - name: mysql-init-volume
          configMap:
            name: mysql-init-script