apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
spec:
  storageClassName: {{ .Values.database.pvc.storageClassName }}
  accessModes:
    - {{ .Values.database.pvc.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.database.pvc.storageSize }}