apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.serviceName }}
spec:
  selector:
    app.kubernetes.io/name: MySQL
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.targetPort }}