apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-aws-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-my  
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "my-app/production-secrets" 
